# Site settings
title: Pablo Martínez-Agulló
description: 'PhD in Physics | Deep Learning Scientist | Data Analysis'
short_description: "Business Card Page"
url: 'http://localhost:4000"'
baseurl: ''
profilepic: '/images/pma.jpg'
bkimage: '/images/bk1.jpg'
#google_analytics: UA-XXXXXX-X
#font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Pablo Martínez Agulló'
  email: pablo.martinez.agullo@gmail.com
  #mastodon: @mstdn.social
  #twitter_username: Pabloaaah
  #facebook_username: ValenciaBanyada
  github_username:  MartinezAgullo
  linkedin_username:  pablo-martinez-agullo
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate

exclude:
  - README.md
  - Gemfile
  - screenshot-overview.png
